### ISSUE TITLE
Kodi 19 support?

### ISSUE THREAD

**Issue by starto711** [beam-kodi-addons-repository/repository-packages#121]
Zdravim,
ma toto repo podporu na kodi 19? Pouzivam kodi 19 verziu zo 17.1.2021 na apple tv avsak pri pokusoch o pridanie zo zip suboru to konci error hlaskou:
Failed to install Add-on from zip file
Installing the Add-on from zip fila located at xxx failed due to an invalid structure.
Dakujem pekne za usmernenie, pomoc.

**Comment by beam** [comment]
Podpora pro Kodi 19 bude az vyjde OSMC s Kodi 19.. pocitam, ze tak nejak +- s finalnim releasem 19.

**Comment by starto711** [comment]
Vdaka za odpoved!
Dufam ze sa poponahlaju a bude to coskoro :)
