### ISSUE TITLE
Matrix support for Edna subtitles

### ISSUE THREAD

**Issue by Pwnz74** [beam-kodi-addons-repository/repository-packages#123]
Hey,
can you please update Edna rep. for new Matrix version of Kodi?

Thank you

**Comment by beam** [comment]
Je to v planu.. pocitam, ze behem tydne se k tomu dostanu.

**Comment by beam** [comment]
zkus.. https://github.com/beam-kodi-addons-repository/service.subtitles.edna.cz/releases
