### ISSUE TITLE
Repository v Kodi vypada, ze je prazdne...

### ISSUE THREAD

**Issue by ariael** [beam-kodi-addons-repository/repository-packages#126]
Asi chyba nekde... Repository jde nainstalovat, ale je prazdne.
Reinstalaci jsem zkousel.
Pouzity je Kodi 19

Diky

**Comment by beam** [comment]
Repositar jeste neni upgradovany na 19, jeste nemam vymysleny jak to udelat, protoze ho chci drzet i pro 18.

**Comment by ariael** [comment]
Aha to chapu. Ale co to treba alespon docasne rozdelit? Pro Titulky.com je tam Kodi 19 verze, ktere nejde takhle stahnout :( Protoze v ZZIP soubory je evidentne spatny HTTPS link

**Comment by beam** [comment]
To uplne nerozumim, co myslim, ze je spatne.
Repositar je v poradku, ale pro 18, tobe se ukazuje jako prazdny asi protoze zadny z doplnku nesplnuje minimalni verzi Pythonu.
 
Kazdopadne tohle https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/releases rucne stazeny a nahrany do Kodi funguje.

**Comment by beam** [comment]
Repo pro 19 rochodim, jen se to musi prozkouset jak se to bude chovat, protoze chci drzet repo pro 18 i 19. Jen nevim jestli to jde dat do jednoho nebo se to musi delit.
