### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by michalss** [beam-kodi-addons-repository/repository-packages#159]
Ahoj,

V repu ti chybi nextweek.cz a ostatni. Muzes to prosim doplnit ?

M

**Comment by beam** [comment]
Doplnky jeste nejsou prepsany pro Kodi 19.x, ja osobne stale jeste jedu na 18.x takze neni zatim motivace je prepisovat.

Na 19.x jsem pripravil jen to co je aktualne v repo.
